### ISSUE TITLE
How to use CreateAPIView?

### ISSUE THREAD

**Issue by JeonChangmin** [swpp-letsstudy/backend#2]
아래와 같은 코드에서 StudyGroup을 만들기 위해서 POST request data에는 어떤 값을 넣어야함?
Auth는 Token으로 되어있는 상태
```python3
class StudyGroupCreate(generics.CreateAPIView):
    permission_classes = (permissions.IsAuthenticatedOrReadOnly, IsUser)
    queryset = StudyGroup.objects.all()
    serializer_class = StudyGroupSerializer
```

```javascript
{
    "name": "created_group",
    "info": "created",
    // "users": [2, 3]
    // "users": 2
    // "users": ["A", "B"]
    // "users": "A"
}
```
위와 같은 POST data를 보낼 경우
```javascript
{
    "users": [
        "This field is required."
    ]
}
```
이런 response가 온다. (state=400)

**Comment by chphch** [comment]
reference this commit 9eb3f645da99dbd59622822b22c15a8ce8f2f943

1. It would be better to use ```ListCreateAPIView``` rather than ```ListAPIView```

2. you can use ```perform_create``` method in ```ListCreateAPIView``` to customize a saving process of the serializer.
[https://www.django-rest-framework.org/api-guide/generic-views/](https://www.django-rest-framework.org/api-guide/generic-views/)

3. ```read_only``` should be set to ```True``` as a parameter of serializer to define a read-only field. Otherwise, ```is_valid``` method would raise an error, and ```save``` or ```update``` methods of serializer would not work.
[https://www.django-rest-framework.org/api-guide/fields/](https://www.django-rest-framework.org/api-guide/fields/)
